site:
  name: The name of your blog
  description: A description
  url: https://example.blog
  copyright: Chris Hannah &copy;
author:
  name: Your name
  link: https://example.blog
postsPerPage: 10
paths: 
  assets:
    assets