site:
  name: The name of your blog
  description: A description
  url: https://example.blog
author:
  name: Your name
  link: https://example.blog
  twitter: 
postsPerPage: 10
paths: 
  assets:
    assets
outputDirectory: out/
showFullContentOnIndex: true